NAME: 3DSEnet

DIRS:
  DATA: './Split_data'
  WEIGHTS: './weights/'
  OUTPUTS: './outputs/'
  LOGS: './logs/'

DATA:
  DEBUG: False
  INP_CHANNEL: 32
  SIZE: (128, 128)

  CSV:
    TRAIN: "Split_data/data_3d/train.csv"
    VALID: "Split_data/data_3d/valid_drop.csv"
    # VALID: "Split_data/data_3d/valid.csv"
    TEST: "Split_data/data_3d/valid_drop.csv"

TRAIN:
  NUM_CYCLES: 1
  EPOCHES: 100
  BATCH_SIZE: 2

SOLVER:
  OPTIMIZER: 'adam'
  SCHEDULER: 'cyclical'
  WARMUP_LENGTH: 0
  GD_STEPS: 1
  BASE_LR: 1e-3
  WEIGHT_DECAY: 1e-2
  WEIGHT_DECAY_BIAS: 0.0
  
LOSS:
  NAME: 'ce'

MODEL:
  NAME: "3D"
  PRETRAINED: False
  NUM_CLASSES: 4