NAME: EfficientNet_b0_base_ww_400_wc_50

SYSTEM:
  GPU: True

DIRS:
  DATA: './Split_data'
  WEIGHTS: './weights/'
  OUTPUTS: './outputs/'
  LOGS: './logs/'

DATA:
  DEBUG: False
  INP_CHANNEL: 3
  SIZE: (512, 512)

  CSV:
    TRAIN: "Split_data/data_100/train.csv"
    VALID: "Split_data/data_100/valid.csv"
    TEST: "Split_data/data_100/test.csv"

TRAIN:
  NUM_CYCLES: 1
  EPOCHES: 100
  BATCH_SIZE: 6
  # BATCH_SIZE: 60

SOLVER:
  OPTIMIZER: 'adam'
  SCHEDULER: 'cyclical'
  WARMUP_LENGTH: 0
  GD_STEPS: 1
  BASE_LR: 7e-3
  WEIGHT_DECAY: 1e-2
  WEIGHT_DECAY_BIAS: 0.0
  
LOSS:
  NAME: 'ce'
  WEIGHTED_LOSS: False
  CLASS_BALANCED_BETA: 0.9

MODEL:
  NAME: "resnet18"
  PRETRAINED: False
  NUM_CLASSES: 3
  POOL: 'adaptive_pooling'
  DROPOUT: 0.0
  DROPPATH: 0.0