NAME: Resnet_18_3d_224

SYSTEM:
  GPU: True

DIRS:
  DATA: './Split_data'
  WEIGHTS: './weights/'
  OUTPUTS: './outputs/'
  LOGS: './logs/'

DATA:
  DEBUG: False
  INP_CHANNEL: 32
  SIZE: (224, 224)

  CSV:
    TRAIN: "Split_data/data_supplement_3d_fix/train.csv"
    VALID: "Split_data/data_supplement_3d_fix/valid.csv"
    TEST: "Split_data/data_supplement_3d_fix/valid.csv"

TRAIN:
  NUM_CYCLES: 1
  EPOCHES: 100
  BATCH_SIZE: 2

SOLVER:
  OPTIMIZER: 'adam'
  SCHEDULER: 'cyclical'
  WARMUP_LENGTH: 0
  GD_STEPS: 1
  BASE_LR: 5e-3
  WEIGHT_DECAY: 1e-2
  WEIGHT_DECAY_BIAS: 0.0
  
LOSS:
  NAME: 'ce'
  WEIGHTED_LOSS: False

MODEL:
  NAME: "3D"
  PRETRAINED: False
  NUM_CLASSES: 3