NAME: Resnet_18_512

SYSTEM:
  GPU: True

DIRS:
  DATA: './Split_data'
  WEIGHTS: './weights/'
  OUTPUTS: './outputs/'
  LOGS: './logs/'

DATA:
  DEBUG: True
  INP_CHANNEL: 3
  SIZE: (512, 512)

  CSV:
    TRAIN: "Split_data/data/train.csv"
    VALID: "Split_data/data/valid.csv"
    TEST: "Split_data/data/valid.csv"

TRAIN:
  NUM_CYCLES: 1
  EPOCHES: 15
  BATCH_SIZE: 32

SOLVER:
  OPTIMIZER: 'adam'
  SCHEDULER: 'cyclical'
  WARMUP_LENGTH: 0
  GD_STEPS: 1
  BASE_LR: 1e-3
  WEIGHT_DECAY: 1e-2
  WEIGHT_DECAY_BIAS: 0.0
  
LOSS:
  NAME: 'ce'
  WEIGHTED_LOSS: False

MODEL:
  NAME: "resnet18"
  PRETRAINED: False
  NUM_CLASSES: 4